version: "3.7"

services:

    influxdb:
        container_name: influxdb
        image: influxdb:1.8
        ports:
            - "8086:8086"
        networks:
            - network_prod
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=${INFLUXDB_DATABASE}
            # - INFLUXDB_USER=grafana
            # - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
            - INFLUXDB_ADMIN_ENABLE=true

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
            - "9001:9001"
            - "10883:1883"
            - "10884:1884"
        networks:
            - network_prod
        volumes:
            - ./data/mosquitto/data:/mosquitto/data
            # - ./data/mosquitto/logs:/mosquitto/logs
            - ./data/mosquitto/config:/mosquitto/config
            - ./data/mosquitto/authen:/mosquitto/authen

    telegraf:
        container_name: telegraf
        image: telegraf
        depends_on: 
            - influxdb
            - mosquitto
        networks:
            - network_prod
        volumes:
            - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        depends_on: 
            - telegraf
        ports: 
            - "3000:3000"
        networks:
            - network_prod
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

networks:
    network_prod: