version: "3.7"

services:

    influxdb:
        container_name: influxdb
        image: influxdb:latest
        ports:
            - '8086:8086'
        networks:
            - monitoring
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=db
            # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
            - 9001:9001
            - 10883:1883
        networks:
            - monitoring

    telegraf:
        container_name: telegraf
        image: telegraf
        depends_on: 
            - influxdb
            - mosquitto
        networks:
            - monitoring
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        depends_on: 
            - telegraf
        ports: 
            - "3000:3000"
        networks:
            - monitoring
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

networks:
    monitoring: